version: "3"
services:
  ldwizard:
    build: .
    volumes:
      - ./:/home/node/app
    ports:
      - 4000:4000
    working_dir: /home/node/app
    command: bash -c "yarn add better-npm-run && yarn dev"